name: flutter_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  logging: ^1.2.0
  http: ^1.3.0
  table_calendar: ^3.0.9
  image_picker: ^1.1.2
  file_picker: ^9.0.2
  speech_to_text: ^7.0.1
  font_awesome_flutter: ^10.8.0
  http_parser: ^4.0.0
  path: ^1.8.2
  flutter_secure_storage: ^8.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.0.0
  intl_phone_field: ^3.2.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.14
  android_intent_plus: ^4.0.3
  mime: ^1.0.5
  package_info_plus: ^8.3.0
  intl: ^0.19.0
  share_plus: ^10.1.4
  timezone: ^0.9.4
  shimmer: ^3.0.0
  flutter_background_service: ^5.0.9
  flutter_background_service_android: ^6.3.0
  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.3.1
  flutter_timezone: ^4.1.0
  firebase_core: ^3.12.1
  firebase_vertexai: ^1.4.0
  firebase_app_check: ^0.3.2+4
  vertex_ai: ^0.1.0+3
  flutter_webrtc: 0.13.0
  cloud_firestore: 5.6.5
  uuid: 4.5.1
  firebase_auth: 5.5.1
  google_sign_in: 6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/doctor.png
    - assets/google.png
    - assets/microsoft.png
    - assets/apple.png
    - assets/back.png
    - assets/doctor1.png
    - assets/doctor2.png
    - assets/google_lens.png
    - assets/ellipse.png
    - assets/image.png
    - assets/.env
    - assets/medicine.png
    - assets/backshape.png
    - assets/specialist.png
    - assets/ai_doctor.png
    - assets/ravindra.png
    - assets/nitesh.png