// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlxciXmBtCx7v7wM3OGXXdj3P_QjHRmk',
    appId: '1:709701253315:web:a7db414e7e5ddadd810a76',
    messagingSenderId: '709701253315',
    projectId: 'telemedicine-ai-api',
    authDomain: 'telemedicine-ai-api.firebaseapp.com',
    storageBucket: 'telemedicine-ai-api.firebasestorage.app',
    measurementId: 'G-D7S9QR294P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoKwvOXVtPWWamNepODigaW8goBNVK-VQ',
    appId: '1:709701253315:android:71cf7de37c1986f6810a76',
    messagingSenderId: '709701253315',
    projectId: 'telemedicine-ai-api',
    storageBucket: 'telemedicine-ai-api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQOK6KhhnOzm6kkRxSrTUKVz5KnNIwDg',
    appId: '1:709701253315:ios:5432476914736d9b810a76',
    messagingSenderId: '709701253315',
    projectId: 'telemedicine-ai-api',
    storageBucket: 'telemedicine-ai-api.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQOK6KhhnOzm6kkRxSrTUKVz5KnNIwDg',
    appId: '1:709701253315:ios:5432476914736d9b810a76',
    messagingSenderId: '709701253315',
    projectId: 'telemedicine-ai-api',
    storageBucket: 'telemedicine-ai-api.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHlxciXmBtCx7v7wM3OGXXdj3P_QjHRmk',
    appId: '1:709701253315:web:a6a40e425b108b17810a76',
    messagingSenderId: '709701253315',
    projectId: 'telemedicine-ai-api',
    authDomain: 'telemedicine-ai-api.firebaseapp.com',
    storageBucket: 'telemedicine-ai-api.firebasestorage.app',
    measurementId: 'G-KJ7HEMEVXE',
  );
}
